# docker-compose.yml
# This file defines the services, networks, and volumes for the Docker application.

version: '3.8'

services:

web:
  image: Commercial-Website-Project1
  build:
    context: .
    dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: always


